server:
  port: 8081

service:
  version: '@project.version@'

spring:
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:postgresql://${PSQL_DATASOURCE_URL}:5432/MicroAuthDB
    username: ${PSQL_DATASOURCE_USERNAME}
    password: ${PSQL_DATASOURCE_PASSWORD}
#  liquibase:
#    change-log: classpath:db.migration/db.changelog-master.xml
#    database-change-log-lock-table: LIQ_DATABASECHANGELOGLOCK
#    database-change-log-table: LIQ_DATABASECHANGELOG
#    driver-class-name: org.postgresql.Driver
#    liquibase-schema: public
#    password: ${spring.datasource.password}
#    url: ${spring.datasource.url}
#    user: ${spring.datasource.username}
  servlet:
    multipart:
      max-file-size: 5MB

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_URL}:9001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    preferIpAddress: true
